const products = {
  products: [
    {
      id: 1,
      name: "Gayo Arabica Coffee",
      description: "Premium coffee with a distinctive flavor from the highlands of Gayo, Aceh.",
      price: 75000,
      weight: "250g",
      stock: 50,
      category: "Arabica",
      rating: 4.8,
      image_url: "https://example.com/images/arabica-gayo.jpg",
    },
    {
      id: 2,
      name: "Lampung Robusta Coffee",
      description: "High-quality Robusta coffee with a strong aroma and bold taste.",
      price: 55000,
      weight: "250g",
      stock: 100,
      category: "Robusta",
      rating: 4.5,
      image_url: "https://example.com/images/robusta-lampung.jpg",
    },
    {
      id: 3,
      name: "Nusantara Blend Coffee",
      description:
        "A blend of the best Arabica and Robusta beans from various regions in Indonesia.",
      price: 60000,
      weight: "250g",
      stock: 75,
      category: "Blend",
      rating: 4.7,
      image_url: "https://example.com/images/blend-nusantara.jpg",
    },
    {
      id: 4,
      name: "Premium Luwak Coffee",
      description: "Exclusive coffee with a unique taste from natural fermentation by civet cats.",
      price: 500000,
      weight: "100g",
      stock: 10,
      category: "Luwak",
      rating: 5.0,
      image_url: "https://example.com/images/luwak-premium.jpg",
    },
    {
      id: 5,
      name: "Cold Brew Coffee",
      description: "Ready-to-drink cold coffee with a refreshing taste.",
      price: 35000,
      weight: "300ml",
      stock: 200,
      category: "Cold Brew",
      rating: 4.3,
      image_url: "https://example.com/images/cold-brew.jpg",
    },
    {
      id: 6,
      name: "Java Estate Coffee",
      description: "Classic Java coffee with a rich body and mild acidity.",
      price: 70000,
      weight: "250g",
      stock: 80,
      category: "Arabica",
      rating: 4.6,
      image_url: "https://example.com/images/java-estate.jpg",
    },
    {
      id: 7,
      name: "Sumatra Mandheling Coffee",
      description: "Well-known for its earthy and herbal notes, grown in Sumatra.",
      price: 80000,
      weight: "250g",
      stock: 60,
      category: "Arabica",
      rating: 4.9,
      image_url: "https://example.com/images/mandheling.jpg",
    },
    {
      id: 8,
      name: "Bali Kintamani Coffee",
      description: "Citrus-flavored coffee from the volcanic highlands of Bali.",
      price: 85000,
      weight: "250g",
      stock: 40,
      category: "Arabica",
      rating: 4.8,
      image_url: "https://example.com/images/kintamani.jpg",
    },
    {
      id: 9,
      name: "Toraja Kalosi Coffee",
      description: "Unique and full-bodied coffee with low acidity, grown in Toraja.",
      price: 90000,
      weight: "250g",
      stock: 30,
      category: "Arabica",
      rating: 4.9,
      image_url: "https://example.com/images/toraja-kalosi.jpg",
    },
    {
      id: 10,
      name: "Espresso Blend Coffee",
      description: "Perfectly roasted blend for making smooth and rich espresso.",
      price: 65000,
      weight: "250g",
      stock: 100,
      category: "Blend",
      rating: 4.7,
      image_url: "https://example.com/images/espresso-blend.jpg",
    },
  ],
};

export default products;
